[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
ffi = true
fs_permissions = [
  { access = "read", path = "./data" },
]
fuzz_runs = 256
gas_reports = ["*"]
libs = ["lib"]
optimizer = true
optimizer_runs = 10_000
out = "out"
src = "src"
test = "test"

[profile.ci]
fuzz_runs = 1_000
verbosity = 4

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
